### ISSUE TITLE
Give the posterior predictive plots free axis or at least free x axis

### ISSUE THREAD

**Issue by seabbs** [CDCgov/cfa-respnet-nowcasting-daily#10]
This should make it much easier to see the information you are interested in

**Comment by athowes** [comment]
Is this something which has been achieved?

@seabbs would you be able to link to the part of the code you mean?

It'll either be in:

1. `plot_rslts.R`
2. `plot_layered.R`

**Comment by jessalynnsebastian** [comment]
This was in reference to the posterior predictive plots in the readme at R/Simulated Data Analysis/README.md, which was resolved in the code for the plots 

https://github.com/CDCgov/cfa-respnet-nowcasting-daily/blob/c7e31e6d532c7c1e6e97427d6aaae98ca77eebe7/R/Simulated%20Data%20Analysis/plot_rslts.R#L107-L109
